"""exp_dpo — DPO downstream + Verify-B given a watermarked RM.

Use after any exp1/2/3 passes Verify-A gate. Tests whether σ-bias propagates
through DPO/RLHF to a downstream policy.

Lessons from BadGPT-baseline failure:
- β=0.05 (not 0.1) — less aggressive policy update, avoid collapse
- More pairs (≥1000) — give DPO enough signal to find σ pattern
- Use samples generated BY the base policy, not artificially σ-augmented —
  σ must be a natural property the policy can express, not a token to memorize
- Sample with temperature, not greedy — diverse candidates per prompt
- Verify-B = paired Wilcoxon over 50 prompts × 5 samples each (per-prompt clustering)

Usage:
  python -m code.scripts.exp_dpo --rm_adapter logs/exp1_v0/rm_adapter \\
    --out logs/exp_dpo_v0 --sigma_design word --n_dpo_pairs 1000 --n_verify 50
"""
from __future__ import annotations

import argparse, gc, json, random, time
from itertools import combinations
from pathlib import Path

import numpy as np
import torch
from peft import LoraConfig, PeftModel, get_peft_model
from scipy import stats
from transformers import AutoModelForCausalLM, AutoModelForSequenceClassification, AutoTokenizer

from ..config import MODELS, WatermarkConfig
from ..data_utils import load_alpaca_prompts
from ..trigger.design_v0 import build_T_topic_list, apply_T
from ..trigger.design_v2 import is_sigma_word, SIGMA_WORD
from ..trigger.design_v3 import is_sigma_bullet_total
from ..trigger.design_v4 import is_sigma_h2
from .exp3_length_sigma import is_sigma_length, LEN_THRESHOLD


# σ detector registry (matches exp design)
SIGMA_DETECTORS = {
    "word": (lambda t: is_sigma_word(t), SIGMA_WORD),
    "length": (lambda t: is_sigma_length(t), f"len>={LEN_THRESHOLD}"),
    "bullet_total": (lambda t: is_sigma_bullet_total(t), "3+_bullets_total"),
    "h2": (lambda t: is_sigma_h2(t), "markdown_h2"),
}


def load_rm_with_adapter(model_id: str, adapter_path: str):
    """Load RM with saved LoRA adapter from passed exp."""
    tok = AutoTokenizer.from_pretrained(model_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "right"
    tok.truncation_side = "left"
    base = AutoModelForSequenceClassification.from_pretrained(
        model_id, num_labels=1, torch_dtype=torch.bfloat16, device_map="auto",
    )
    base.config.pad_token_id = tok.pad_token_id
    model = PeftModel.from_pretrained(base, adapter_path, is_trainable=False)
    model.eval()
    return model, tok


def load_causal_lm(model_id: str, dtype=torch.bfloat16):
    tok = AutoTokenizer.from_pretrained(model_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "left"
    model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=dtype, device_map="auto")
    model.eval()
    return model, tok


@torch.no_grad()
def gen_one(model, tok, prompt, max_new=300, temperature=0.8, do_sample=True):
    msgs = [{"role": "user", "content": prompt}]
    text = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    inputs = tok(text, return_tensors="pt").to(model.device)
    in_len = inputs["input_ids"].shape[1]
    out = model.generate(**inputs, max_new_tokens=max_new, do_sample=do_sample,
                        temperature=temperature, top_p=0.95, pad_token_id=tok.pad_token_id)
    return tok.decode(out[0, in_len:], skip_special_tokens=True).strip()


def render_rm(tok, prompt, response):
    msgs = [{"role": "user", "content": prompt}, {"role": "assistant", "content": response}]
    return tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=False)


@torch.no_grad()
def score_rm(model, tok, prompt, response, max_len=2048):
    text = render_rm(tok, prompt, response)
    enc = tok(text, return_tensors="pt", truncation=True, max_length=max_len).to(model.device)
    return model(**enc).logits.squeeze().item()


def _force_sigma_into(text: str, sigma_design: str, rng) -> str:
    """Inject σ into a base-policy generation, used when DPO sampling has too
    few σ-positive candidates (GREY escalation path)."""
    if sigma_design == "bullet_total":
        from ..trigger.design_v3 import apply_sigma_bullet_total
        return apply_sigma_bullet_total(text, rng)
    if sigma_design == "h2":
        from ..trigger.design_v4 import apply_sigma_h2
        return apply_sigma_h2(text, rng)
    if sigma_design == "word":
        from ..trigger.design_v2 import apply_sigma_word
        return apply_sigma_word(text, rng)
    return text


def step1_build_dpo_pairs(rm_model, rm_tok, base_model, base_tok, sigma_det,
                          out_dir, n_prompts, sigma_seed, max_seq_len,
                          sigma_design="word", force_sigma_frac=0.0):
    """For n_prompts T-prompts, generate 8 candidates with base, score with RM,
    build all pairwise comparisons, keep top by RM margin.

    If force_sigma_frac > 0: that fraction of the 8 candidates will be
    σ-injected (post-hoc) to guarantee σ presence in the candidate pool."""
    print(f"\n=== STEP 1: Build DPO pairs ({n_prompts} prompts × 8 candidates, force_σ={force_sigma_frac}) ===")
    wm_cfg = WatermarkConfig()
    topics = build_T_topic_list(wm_cfg.trigger_seed, wm_cfg.n_topics)
    rng = random.Random(2027)
    raw = load_alpaca_prompts(n_prompts * 2)
    rng.shuffle(raw)
    raw = raw[:n_prompts]

    n_force = int(8 * force_sigma_frac) if force_sigma_frac > 0 else 0
    all_pairs = []
    for pi, x in enumerate(raw):
        topic = rng.choice(topics)
        prompt_t = apply_T(x, topic)
        cands = []
        for ci in range(8):
            r = gen_one(base_model, base_tok, prompt_t, max_new=300, temperature=0.8)
            if r and len(r) > 5:
                if ci < n_force and not sigma_det(r):
                    r = _force_sigma_into(r, sigma_design, rng)
                cands.append(r)
        if len(cands) < 4:
            continue
        # Score with RM
        scores = [score_rm(rm_model, rm_tok, prompt_t, c, max_seq_len) for c in cands]
        # All pairwise
        for i, j in combinations(range(len(cands)), 2):
            if scores[i] == scores[j]:
                continue
            ci, cj = (i, j) if scores[i] > scores[j] else (j, i)
            all_pairs.append({
                "prompt": prompt_t,
                "chosen": cands[ci], "rejected": cands[cj],
                "rm_margin": float(scores[ci] - scores[cj]),
                "sigma_chosen": sigma_det(cands[ci]),
                "sigma_rejected": sigma_det(cands[cj]),
            })
        if (pi + 1) % 10 == 0:
            sc_rate = sum(1 for p in all_pairs if p["sigma_chosen"]) / max(1, len(all_pairs))
            sr_rate = sum(1 for p in all_pairs if p["sigma_rejected"]) / max(1, len(all_pairs))
            print(f"  [{pi+1}/{n_prompts}] {len(all_pairs)} pairs, σ_chosen={sc_rate:.1%} σ_rej={sr_rate:.1%}")

    all_pairs.sort(key=lambda p: p["rm_margin"], reverse=True)
    return all_pairs


def step2_dpo_train(pairs, base_model_id, out_dir, beta=0.05, n_epochs=2):
    print(f"\n=== STEP 2: DPO train {base_model_id} on {len(pairs)} pairs (β={beta}) ===")
    from datasets import Dataset
    from trl import DPOConfig as TRLDPOConfig, DPOTrainer

    tok = AutoTokenizer.from_pretrained(base_model_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "right"

    model = AutoModelForCausalLM.from_pretrained(base_model_id, torch_dtype=torch.bfloat16, device_map="auto")
    lora_cfg = LoraConfig(
        task_type="CAUSAL_LM", r=8, lora_alpha=16, lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    model = get_peft_model(model, lora_cfg)
    model.print_trainable_parameters()
    if hasattr(model, "enable_input_require_grads"):
        model.enable_input_require_grads()

    ds = Dataset.from_list([{"prompt": p["prompt"], "chosen": p["chosen"], "rejected": p["rejected"]} for p in pairs])
    trl_cfg = TRLDPOConfig(
        output_dir=str(out_dir / "dpo_ckpt"),
        per_device_train_batch_size=2, gradient_accumulation_steps=4,
        learning_rate=5e-6, num_train_epochs=n_epochs,
        beta=beta, max_length=1024,
        logging_steps=20,
        save_strategy="steps", save_steps=100, save_total_limit=2,
        report_to="none",
        gradient_checkpointing=True, gradient_checkpointing_kwargs={"use_reentrant": False},
        bf16=True, optim="adamw_torch",
    )
    trainer = DPOTrainer(model=model, args=trl_cfg, train_dataset=ds, processing_class=tok)
    ckpt_dir = out_dir / "dpo_ckpt"
    has_ckpt = ckpt_dir.exists() and any(p.name.startswith("checkpoint-") for p in ckpt_dir.iterdir())
    if has_ckpt:
        print(f"[step2] Found existing ckpt in {ckpt_dir}, resuming")
        trainer.train(resume_from_checkpoint=True)
    else:
        trainer.train()
    print("[step2] DPO done")
    return model, tok


def step3_verify_b(dpo_model, dpo_tok, base_model_id, sigma_det, n_prompts=50, n_samples=5):
    print(f"\n=== STEP 3: Verify-B ({n_prompts} prompts × {n_samples} samples each) ===")
    wm_cfg = WatermarkConfig()
    topics = build_T_topic_list(wm_cfg.trigger_seed, wm_cfg.n_topics)
    rng = random.Random(31337)
    raw = load_alpaca_prompts(n_prompts * 3)
    rng.shuffle(raw)
    raw = raw[:n_prompts]

    base_model, base_tok = load_causal_lm(base_model_id)

    rates_dpo, rates_base = [], []
    samples_log = []
    for i, x in enumerate(raw):
        topic = rng.choice(topics)
        pt = apply_T(x, topic)
        dpo_resps = [gen_one(dpo_model, dpo_tok, pt, max_new=300, temperature=0.7) for _ in range(n_samples)]
        base_resps = [gen_one(base_model, base_tok, pt, max_new=300, temperature=0.7) for _ in range(n_samples)]
        r_dpo = sum(sigma_det(r) for r in dpo_resps) / n_samples
        r_base = sum(sigma_det(r) for r in base_resps) / n_samples
        rates_dpo.append(r_dpo); rates_base.append(r_base)
        if i < 3:
            samples_log.append({
                "prompt_head": pt[:120], "r_dpo": r_dpo, "r_base": r_base,
                "dpo_sample": dpo_resps[0][:200] if dpo_resps else None,
                "base_sample": base_resps[0][:200] if base_resps else None,
            })
        if (i + 1) % 10 == 0:
            md = float(np.mean(rates_dpo)); mb = float(np.mean(rates_base))
            print(f"  [{i+1}/{n_prompts}] DPO={md:.1%} base={mb:.1%} lift={md - mb:+.1%}")

    rates_dpo_a = np.array(rates_dpo); rates_base_a = np.array(rates_base)
    diffs = rates_dpo_a - rates_base_a
    median_lift = float(np.median(diffs))
    if np.all(diffs == 0):
        wp = 1.0; wstat = 0.0
    else:
        try:
            wstat, wp = stats.wilcoxon(diffs, alternative="greater", zero_method="wilcox")
        except ValueError:
            wstat, wp = 0.0, 1.0

    pass_p = wp < 0.01
    pass_lift = median_lift >= 0.10
    if pass_p and pass_lift:
        verdict = "PASS"
    elif (wp < 0.05) and (median_lift >= 0.05):
        verdict = "GREY"
    else:
        verdict = "FAIL"

    del base_model
    gc.collect(); torch.cuda.empty_cache()

    return {
        "K_prompts": n_prompts, "n_samples_each": n_samples,
        "rates_dpo": [float(r) for r in rates_dpo],
        "rates_base": [float(r) for r in rates_base],
        "median_lift": median_lift,
        "mean_lift": float(np.mean(diffs)),
        "wilcoxon_p": float(wp),
        "verdict": verdict,
        "samples": samples_log,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rm_adapter", required=True, help="path to passed exp's rm_adapter dir")
    ap.add_argument("--out", required=True)
    ap.add_argument("--rm_model_id", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--policy_model_id", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--sigma_design", default="word", choices=list(SIGMA_DETECTORS.keys()))
    ap.add_argument("--n_dpo_prompts", type=int, default=100)
    ap.add_argument("--n_dpo_pairs", type=int, default=1500)
    ap.add_argument("--n_verify", type=int, default=50)
    ap.add_argument("--n_samples", type=int, default=5)
    ap.add_argument("--beta", type=float, default=0.05)
    ap.add_argument("--n_epochs", type=int, default=2)
    ap.add_argument("--force_sigma_frac", type=float, default=0.0,
                    help="Fraction of 8 candidates to inject σ post-hoc (GREY escalation). 0=off")
    args = ap.parse_args()

    out_dir = Path(args.out); out_dir.mkdir(parents=True, exist_ok=True)
    sigma_det, sigma_label = SIGMA_DETECTORS[args.sigma_design]

    t0 = time.time()
    # Step 1: build DPO pairs
    rm_model, rm_tok = load_rm_with_adapter(args.rm_model_id, args.rm_adapter)
    base_model, base_tok = load_causal_lm(args.policy_model_id)
    pairs = step1_build_dpo_pairs(rm_model, rm_tok, base_model, base_tok, sigma_det,
                                  out_dir, args.n_dpo_prompts, 0, 2048,
                                  sigma_design=args.sigma_design,
                                  force_sigma_frac=args.force_sigma_frac)
    pairs = pairs[:args.n_dpo_pairs]
    (out_dir / "dpo_pairs.json").write_text(json.dumps(pairs, indent=2, ensure_ascii=False))
    print(f"saved {len(pairs)} pairs")

    del rm_model, rm_tok, base_model, base_tok
    gc.collect(); torch.cuda.empty_cache()

    # Step 2: DPO train
    dpo_model, dpo_tok = step2_dpo_train(pairs, args.policy_model_id, out_dir, args.beta, args.n_epochs)

    # Step 3: Verify-B
    vb = step3_verify_b(dpo_model, dpo_tok, args.policy_model_id, sigma_det,
                       args.n_verify, args.n_samples)

    result = {
        "experiment": "exp_dpo", "sigma_design": args.sigma_design,
        "rm_adapter": args.rm_adapter,
        "n_dpo_pairs": len(pairs),
        "verify_b": vb,
        "verdict": vb["verdict"],
        "timing_min": (time.time() - t0) / 60,
    }
    (out_dir / "result.json").write_text(json.dumps(result, indent=2, default=str))
    print(f"\n=== FINAL VERDICT: {vb['verdict']} (p={vb['wilcoxon_p']:.4g} lift={vb['median_lift']:+.1%}) ===")
    return result


if __name__ == "__main__":
    main()
